/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const baseURL: typeof import('@/config/config')['baseURL']
  const comm: typeof import('@/utils/common')['comm']
}
