services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "5000"

  nginx:
    image: nginx:1.26.3
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - server
